name: BlogAPI CI/CD

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Venv
        run: python3 -m venv env
      
      - name: Activate Venv
        run: source ./env/bin/activate

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest