name: BlogAPI CI/CD

on:
  push:
    branches: [master]

# CI
jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Venv
        run: python3 -m venv env
      
      - name: Activate Venv
        run: source ./env/bin/activate

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

# CD
  build_and_run_docker:
    runs-on: self-hosted
    steps:
      - name: Build and Run
        run: |
            if [[ -n $( docker images -q blogapp:latest ) ]]; then
              echo 'Container BlogAPP image exists'

              if docker inspect blog_api > /dev/null 2>&1; then
                echo "The container blog_api exists."
                
                # Check if the container is running
                if $(docker inspect -f '{{.State.Status}}' "blog_api" | grep -q "running"); then
                    echo "The container blog_api is running. START STOPING OPERATION"
                    docker stop blog_api
                    echo "The container blog_api START DELETING"
                    docker rm blog_api
                    echo "The container blog_api DELETED"

                    # Deleting old image
                    echo "The old image 'blogapp' START DELETING"
                    docker rmi blogapp
                    echo "The Image 'blogapp' DELETED"
                fi
              fi
              
            fi

            # CREATE NEW Image
            echo "Start build new image 'blogapp'"
            docker build -t blogapp .
            echo "Start running container 'blog_api'"
            docker run -d --name blog_api -p 8000:8282 blogapp
