name: BlogAPI CI/CD

on:
  push:
    branches: [master]

# CI
jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Venv
        run: python3 -m venv env
      
      - name: Activate Venv
        run: source ./env/bin/activate

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
        
      - name: Clean folder
        run: rm -rf /home/dev/actions-runner/_work/blogapp

# CD
  build_and_run_docker:
    runs-on: self-hosted
    steps:
      # - shell: bash
      #   env:
      #     FOLDER_PATH: ${{ secrets.FOLDER_PATH }}
      #     RUNNER_PATH: ${{ vars.RUNNER_PATH }}
      #     TEST: OOOOOOOOOOOPPPPPPPPPP
      - name: Build and Run
        run: |
            if [[ -n $( docker images -q blogapp:latest ) ]]; then
              echo 'Container BlogAPP image exists'

              if docker inspect blog_api > /dev/null 2>&1; then
                echo "The container blog_api exists."
                
                # Check if the container is running
                if $(docker inspect -f '{{.State.Status}}' "blog_api" | grep -q "running"); then
                    echo "The container blog_api is running. START STOPING OPERATION"
                    docker stop blog_api
                    echo "The container blog_api START DELETING"
                    docker rm blog_api
                    echo "The container blog_api DELETED"

                    # Deleting old image
                    echo "The old image 'blogapp' START DELETING"
                    docker rmi blogapp
                    echo "The Image 'blogapp' DELETED"
                fi
              fi
              
            fi

            # CREATE NEW Image
            echo "Start build new image 'blogapp'"
            docker build -t blogapp .
            echo "Start running container 'blog_api'"
            docker run -d --name blog_api -p 8000:8282 blogapp

      - name: Clean folder
        run: rm -rf /home/dev/actions-runner/_work/blogapp

      # - name: Docker run
      #   run: docker run -d --name blog_api -p 8000:8282 blogapp
      # - name: Set env as secret
      #   run: echo ${{env.FOLDER_PATH}} ${{env.RUNNER_PATH}} ${{env.TEST}}

      # - name: Test run
      #   run: echo "$FOLDER_PATH" "$RUNNER_PATH" "$TEST"
        
      # - name: Clean Filesystem
      #   # run: rm -rf ${{ secrets.FOLDER_PATH }}/
      #   run: echo ">>> ${{ vars.FOLDER_PATH }}"
  # test_env:
  #   runs-on: self-hosted
  #   steps:
  #     - shell: bash
  #       env:
  #         FOLDER_PATH: /home/dev/actions-runner/_work/blogapp
  #       run: |
  #         echo "$FOLDER_PATH" "$RUNNER_PATH" "${{env.FOLDER_PATH}}" "${{env.RUNNER_PATH}}"
  #         rm -rf $FOLDER_PATH
