name: BlogAPI CI/CD

on:
  push:
    branches: [master]

# CI
jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Venv
        run: python3 -m venv env
      
      - name: Activate Venv
        run: source ./env/bin/activate

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

# CD
  build_and_run_docker:
    runs-on: self-hosted
    steps:
      - name: Docker build operations
        run: docker build -t blogapp .

      - name: Docker run
        run: docker run -d -p 8000:8282 blogapp
      
      - name: Clean Filesystem
        run: rm -rf ${{secrets.BLOGAPP_PATH}}/blogapp/

